### PR TITLE
Add save()-Function

### PR DESCRIPTION
**Pull request by Wusch**
The function gets the related fields and there values then safes the model and afterwards sets the related values.

### CODE REVIEW

**Comment by Toflar** [comment]
Thank you for your contribution! Things to fix before we can merge it into develop:

* Add the doc block for the `save()` method
* Add line breaks between the lines
* Move the `is_array` check to the `__set()` method an throw an `InvalidArgumentException` if it's not an array.

**Comment by Toflar** [comment]
> Move the is_array check to the __set() method an throw an InvalidArgumentException if it's not an array.

This is still open, I cannot merge it that way.

**Comment by Wusch** [comment]
Like i said in my last commit: If we move the check to the __set() method we will delete our related values if we save our model again because the value of our field is empty.

**Comment by Toflar** [comment]
Added to develop in https://github.com/codefog/contao-haste/commit/e6978fc651b84653bc087e9a4939279918855007

**Pull request merged**
