### PR TITLE
Added RepositoryVersion class and unit test

### PR DESCRIPTION
**Pull request by aschempp**
Extracted the Repository Version formatting methods and added encode version and unit test. Plz provide feedback :-)

/cc @qzminski @Toflar

### CODE REVIEW

**Comment by qzminski** [comment]
Looks good to me. I just wonder why is it ```$aVersion``` and not ```$version``` ?

**Comment by aschempp** [comment]
well the code is duplicated and has always been that. But I can change it if you prefer :-)

**Comment by Toflar** [comment]
> But I can change it if you prefer :-)

I do too but other than that it looks good :)

**Comment by qzminski** [comment]
:+1: for variable name change

**Comment by aschempp** [comment]
Done

**Pull request merged**
