### PR TITLE
Dimensions, Volumes & EAN

### PR DESCRIPTION
**Pull request by craidler-radconsulting**

### CODE REVIEW

**Comment by craidler-radconsulting** [comment]
1. http://www.robert-kuhlemann.de/iso_masseinheiten.htm
2. Did i get the Scale.php wrong in its purpose (did not think too long about it) or don't we need to be capable of compairing apples with carrots on dimensions too? So is 2.134 inch less than 23.348 millimeters?

**Comment by aschempp** [comment]
Well we might want the options to compare, but a scale (=> ⚖️ ) is not a thing for dimensions 😉 

Also, what about square measurements etc? Do you think that would be part of "Dimensions"?

**Comment by craidler-radconsulting** [comment]
I'd say areas and volumes should be ... areas and volumes as they consist of dimensions.

**Comment by qzminski** [comment]
Thanks @craidler-radconsulting !

**Comment by aschempp** [comment]
I'm looking at this since ot got lost in Haste version 5, can anyone tell me what this EAN class is supposed to be or do? EAN to me is the _European Article Number_, but that hardly makes sense in _units to convert_?

**Pull request merged**
