### PR TITLE
add utility classes for dca sorting modes and flags

### PR DESCRIPTION
**Pull request by Tastaturberuf**
add readable sorting modes and flags for using in the dca files

### CODE REVIEW

**Comment by qzminski** [comment]
That's a good idea but I think this should rather be a Contao core code. @Toflar @aschempp

**Comment by Tastaturberuf** [comment]
I think the same but i want to have it asap and in older contao versions like 3.5 LTS and 4.4 LTS. That's why this is also a 'haste' feature.

**Comment by aschempp** [comment]
I like the idea and I'm fine with adding it to Haste. But I think the constant names should be shorter and the classes should be in `Haste\Dca` namespace.

**Comment by qzminski** [comment]
I agree with moving it to the `Dca` namespace. Also, the names could be shortened a bit:

```
NOT_SORTED => NONE
SORTED_FIXED_FIELD => FIXED_FIELD
SORTED_SWITCHABLE_FIELD => SWITCHABLE_FIELD
SORTED_PARENT_TABLE => PARENT_TABLE
DISPLAY_AS_CHILD => CHILD_VIEW
DISPLAY_AS_TREE => TREE_VIEW
DISPLAY_AS_CHILD_TREE => CHILD_TREE_VIEW
```

**Comment by Tastaturberuf** [comment]
Thanks for the feedback. I update the PR

**Comment by qzminski** [comment]
Thanks @Tastaturberuf !

**Comment by qzminski** [comment]
I have just released 4.19.0.

**Pull request merged**
