### PR TITLE
PHP8 compat

### PR DESCRIPTION
**Pull request by m-vo**
This is a first attempt at gaining PHP8 support.

* I had to raise the PHPUnit version and adjust the tests (changes in 07043c8 must have failed before IMHO).
* I also dropped support for PHP5.6 (no actively supported Contao version runs on this version anymore). This allows use of the null coalescing operator.
* I tried to spot as many array access problems as I could find in a first run. 100% sure there are still more things in there but I hope it's a valuable start. This will probably need patching over time as soon as errors occur. 

There are quite a lot of deprecated things in the codebase (esp with Contao >= 4.9 in mind) or things that could be optimized. I did not touch any of these things in this PR (and do not intend to). :slightly_smiling_face:

### CODE REVIEW

**Comment by m-vo** [comment]
Travis would need to be adjusted as well. If you need tests to run on PHP version other than >=7.3 this would also need the Sf phpunit-bridge or a similar mechanic. But well...

**Comment by aschempp** [comment]
> Travis would need to be adjusted as well. If you need tests to run on PHP version other than >=7.3 this would also need the Sf phpunit-bridge or a similar mechanic. But well...

Not really necessary imho. We can remove Travis in my opinion.

**Review by aschempp — APPROVED** [review]
Looks good to me, nothing I wouldn't merge 😊

**Review by qzminski — APPROVED** [review]
I would prefer 

```php
isset($GLOBALS['TL_DCA'][$table]['config']['onundo_callback']) && is_array($GLOBALS['TL_DCA'][$table]['config']['onundo_callback'])
```

 instead of 

```php
is_array($GLOBALS['TL_DCA'][$table]['config']['onundo_callback'] ?? null)
``` 

everywhere, but that's a lot of more work, so I'm also fine with your current changes :+1:

**Comment by qzminski** [comment]
Let's test this directly in the battle, just released as 4.24.14 :+1: thank you @m-vo !

**Pull request merged**
