### PR TITLE
Changed \String::* calls to \StringUtil for PHP7 compatibility reasons

### PR DESCRIPTION
**Pull request by bytehead**
PHP 7 compatibility - see contao/core-bundle#309.

### CODE REVIEW

**Comment by aschempp** [comment]
I think StringUtil has been introduced in Contao 3.5.2 ?

**Comment by bytehead** [comment]
Hmm, that could be. But full PHP7-compat was introduced with 3.5.5 afaik.

**Comment by bytehead** [comment]
Actually [3.5.1](https://github.com/contao/core/blob/007b2af22011307e2f2ccbf39a15823c717aeb28/system/docs/CHANGELOG.md)...

**Comment by aschempp** [comment]
3.5.5, true: https://github.com/contao/core/issues/8018

**Comment by Toflar** [comment]
Imho we can also increase the minimum compatibility to 3.5.5. All the other extensions that use the String class and want to be compatible with PHP7 are very likely to be at least 3.5.5 instead of using `version_compare()` anyway too? What are your opinions? Time to move on, maybe?

**Comment by bytehead** [comment]
Moving on sounds great for me. I don't know, how many others use this extension. By the way, it's a bc break, isn't it?

**Comment by aschempp** [comment]
It's not a BC break because the Haste API does not change. Only the dependencies change, and Composer will take care of that.

However, I'm pretty sure people still use Haste in older versions (likely we do, too), so… dunno…

**Comment by Toflar** [comment]
No BC break but yes, you cannot update to that version anymore then without moving on. But in that case you are using a long outdated Contao version that probably needs to be updated anyway. Is it just this piece of code for PHP7 compat?

**Comment by bytehead** [comment]
I think so. I'm not sure about the `func_get_args()` [here](https://github.com/codefog/contao-haste/blob/master/library/Haste/Model/Relations.php#L348) - as Julien Pauli from SensioLabs states a behavioural change in his [talk](http://de.slideshare.net/jpauli/php7-is-coming) ([direct link](http://image.slidesharecdn.com/php7-150513153139-lva1-app6892/95/php7-is-coming-55-638.jpg?cb=1446039780) to Slide 55).
The assignment (`$dc = $arg;`) looks not affected to me. Your opinion?

**Comment by Toflar** [comment]
Should not, no :) Thx for the link btw :) Well then, we would increase the dependencies just for that one piece of code where we could easily live with a `version_compare`, right? Then I'd just leave it as is.

**Comment by bytehead** [comment]
No worries :) I can easily live with a `version_compare`. We could could mark it _to be removed_ in a next major version.

**Comment by bytehead** [comment]
Update version with correct version compare (inclusive `BUILD` number). See [comment](https://github.com/contao-community-alliance/events-contao-bindings/pull/10#discussion_r52897571) from @discordier.

**Comment by fritzmg** [comment]
But shouldn't it still be compared with version `3.5.1` technically, as this particular change only regards the `String` class usage, which is available in Contao `3.5.1`?

**Comment by qzminski** [comment]
@aschempp @Toflar so what do we finally do with this issue? Shall I merge this PR or do you have any extra feedback?

@fritzmg perhaps it could be compared to ```3.5.1``` as well (not sure about the Andy's comment though https://github.com/codefog/contao-haste/pull/79#issuecomment-182368680) but what I'd recommend more is to update your installation to ```3.5.11``` anyway as no BC break is there compared to ```3.5.1``` ;-)

**Comment by fritzmg** [comment]
> @fritzmg perhaps it could be compared to 3.5.1 as well (not sure about the Andy's comment though #79 (comment)) but what I'd recommend more is to update your installation to 3.5.11 anyway as no BC break is there compared to 3.5.1 ;-)

I know, but technically `Contao\StringUtil` is available since Contao `3.5.1` so imho that's the version it should be compared to - but it doesn't matter in the end anyway :)

**Comment by qzminski** [comment]
Merged in dcda68c.

**Pull request closed without merging**
